### ISSUE TITLE
Issue deploying locally with docker

### ISSUE THREAD

**Issue by vemonet** [MillenniumDB/MillenniumDB#28]
I tried to deploy MilleniumDB locally to test and debug federated query from MDB to a custom SPARQL endpoint

I followed instructions from https://mdb.imfd.cl/doc/docs/docker.html

Here is my `compose.yml` definition, I have put a dummy `toast.ttl` file with 1 triple in the data folder since it seems MDB requires a file to create a repository

```yml
services:
  millenniumdb:
    image: imfd/millenniumdb
    ports:
      - 1234:1234
      - 4321:4321
    # entrypoint: mdb-import /data/toast.ttl /data/toast && mdb-server
    entrypoint: mdb-import /data/toast.ttl /data/toast && mdb-cli /data/toast
    volumes:
      - ./data:/data
```

I am getting this error, absolutely no other logs

```
millenniumdb-1 exited with code 132
```

Is it too soon to do this or I am doing something wrong?

**Comment by cirojas** [comment]
the `imfd/millenniumdb` image has not been updated for a while, so for now you will have to build it:

```bash
docker build -t mdb .
```

Then you can use docker compose, but for some reason mdb-cli is not working as expected, but mdb-server works for me
```yaml
services:
  millenniumdb:
    image: mdb
    ports:
      - 1234:1234
      - 4321:4321
    command: >
      bash -c "
       [ ! -d "/data/toast" ] && mdb-import /data/toast.ttl /data/toast;
       mdb-server /data/toast;
      "
    volumes:
      - ./data:/data
```

To use mdb-cli, try this:
```bash
docker run -it --rm --volume ./data:/data mdb mdb-cli /data/toast
```
